### PR TITLE
Switched to submodules & added Centos 6.2 support

### PR DESCRIPTION
**Pull request by lynxbat**

### CODE REVIEW

**Comment by benburkert** [comment]
I switched to using [librarian-puppet](https://github.com/rodjek/librarian-puppet) for managing the modules, hopefully this keeps things more up to date without the hassle of dealing with submodules. Thanks for the PR, I merged in the updated microkernel change.

**Comment by lynxbat** [comment]
Nice. Only went that route because a ton of fixes have gone into the
puppet modules for Razor. I prefer not messing with submods too if I
can help it.

Nicholas Weaver

On Jul 13, 2012, at 12:33, Ben Burkert
reply@reply.github.com
wrote:

**Comment by benburkert** [comment]
ahh, should I pull in the razor module from git instead of forge.puppetlabs.com? Right now it's pulling in v0.1.4.

**Comment by lynxbat** [comment]
Since Vagrant is usually for dev use. I would say yes. The github gets updated by Nan pretty quick. While the forge updates take longer.

## 

Nicholas Weaver
EMC Corporation

**Comment by benburkert** [comment]
done.

**Pull request closed without merging**
